name = "Turtles"
uuid = "37f3a7ca-22fe-4915-8a8b-6f135989f045"
authors = ["gm-at-tau <gm@mail.tau.ac.il>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
